all:
	gcc -g -Wall -Werror -o quadtree functiiArbore.c main.c functiiC1.c functiiC2.c functiiC3.c functiiCoada.c -lm

build: functiiArbore.c main.c functiiC1.c functiiC2.c functiiC3.c functiiCoada.c
	gcc -g -Wall -Werror -o quadtree functiiArbore.c main.c functiiC1.c functiiC2.c functiiC3.c functiiCoada.c -lm

clean:
	rm -r quadtree
